version: '3'

services:
  configurationproject:
    image: configurationproject
    build:
      context: ./ConfigurationProject
      dockerfile: Dockerfile
    ports:
      - "8035:80" 
  db:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - .:/setup
      command: --auth